text_sensor:
  - platform: homeassistant
    id: dial_light_office_state
    entity_id: light.desk_led_strip
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_living_room_state
    entity_id: light.living_room_light_group
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_bedroom_state
    entity_id: light.bedroom_light_group
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_office_modes
    entity_id: light.desk_led_strip
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_modes
    entity_id: light.living_room_light_group
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_modes
    entity_id: light.bedroom_light_group
    attribute: supported_color_modes
    internal: true

  - platform: homeassistant
    id: dial_light_office_rgb
    entity_id: light.desk_led_strip
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_rgb
    entity_id: light.living_room_light_group
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_rgb
    entity_id: light.bedroom_light_group
    attribute: rgb_color
    internal: true

  - platform: homeassistant
    id: dial_light_office_color_mode
    entity_id: light.desk_led_strip
    attribute: color_mode
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_color_mode
    entity_id: light.living_room_light_group
    attribute: color_mode
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_color_mode
    entity_id: light.bedroom_light_group
    attribute: color_mode
    internal: true

sensor:
  - platform: homeassistant
    id: dial_light_office_brightness
    entity_id: light.desk_led_strip
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_living_room_brightness
    entity_id: light.living_room_light_group
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_bedroom_brightness
    entity_id: light.bedroom_light_group
    attribute: brightness
    internal: true
    on_value:
      - script.execute: menu_on_ha_update

  - platform: homeassistant
    id: dial_light_office_color_temp_kelvin
    entity_id: light.desk_led_strip
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_color_temp_kelvin
    entity_id: light.living_room_light_group
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_color_temp_kelvin
    entity_id: light.bedroom_light_group
    attribute: color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_office_min_color_temp_kelvin
    entity_id: light.desk_led_strip
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_min_color_temp_kelvin
    entity_id: light.living_room_light_group
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_min_color_temp_kelvin
    entity_id: light.bedroom_light_group
    attribute: min_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_office_max_color_temp_kelvin
    entity_id: light.desk_led_strip
    attribute: max_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_living_room_max_color_temp_kelvin
    entity_id: light.living_room_light_group
    attribute: max_color_temp_kelvin
    internal: true

  - platform: homeassistant
    id: dial_light_bedroom_max_color_temp_kelvin
    entity_id: light.bedroom_light_group
    attribute: max_color_temp_kelvin
    internal: true
